#!/usr/bin/env bash
#
# Find and fix trailing whitespace in commits. Bypass with
# git commit --no-verify.
#

if git-rev-parse --verify HEAD >/dev/null 2>&1 ; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

is_ready=true
# Handle filenames with spaces
# http://www.cyberciti.biz/tips/handling-filenames-with-spaces-in-bash.html
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
# Find files with trailing whitespace
# On Windows, you need core.whitespace=cr-at-eol
for FILE in `exec git diff-index --check --cached $against -- | sed '/^[+-]/d' | sed -r 's/:[0-9]+:.*//' | uniq` ; do
    # Fix them!
    # -b and \r are to preserve Windows line endings.
    sed -bi 's/[ \t]\+\(\r\?\)$/\1/' "$FILE"
    is_ready=false
done
IFS=$SAVEIFS

if [ "$is_ready" = "false" ]; then
    echo -e "\nTrailing whitespace removed. Add and commit."
    exit 1
fi
