#!/usr/bin/env bash
#
# Find and fix trailing whitespace in commits. Bypass with
# git commit --no-verify.
#
# On Windows, if you need to store newlines as \r\n for some reason, you need the following:
# -gitconfig core.whitespace+=cr-at-eol
# -Pass -b to sed

if git-rev-parse --verify HEAD >/dev/null 2>&1 ; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

is_ready=true
# Handle filenames with spaces
# http://www.cyberciti.biz/tips/handling-filenames-with-spaces-in-bash.html
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
# Find files with issues
for FILE in `exec git diff-index --check --cached $against -- | gsed '/^[+-]/d' | gsed -r 's/:[0-9]+:.*//' | uniq` ; do
    # Remove trailing whitespace
    gsed -bi 's/[ \t]\+\(\r\?\)$/\1/' "$FILE"
    # Remove trailing newlines
    TMP_FILE="$FILE".pre-commit
    tac "$FILE" | gsed '0,/./s/^$/872d91b2399e7cde/;/872d91b2399e7cde/d' | tac >"$TMP_FILE"
    mv "$TMP_FILE" "$FILE"
    is_ready=false
done
IFS=$SAVEIFS

if [ "$is_ready" = "false" ]; then
    git diff-index --check --cached $against --
    echo -e "\nTrailing whitespace removed. Add and commit."
    exit 1
fi
